[package]
name = "aquaDB"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aqua"
path = "src/lib/lib.rs"

[[bin]]
name = "aquaDB"
path = "src/bin/main.rs"

[dependencies]
positioned-io2 = "0.3.4"
# nix = "0.25.0"
chrono = "0.4.22"
log = "0.4.17"
btreemultimap = "0.1.0"